kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: raouagara/spring
      imagePullSecrets:
        - name: registry-secret imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: spring
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
  selector:
    app: spring
