apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spring-boot-mongo-docker
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spring-boot-mongo-docker
    spec:
      containers:
      - image: raouagara/spring-boot-mongo
        name: spring-boot-mongo-docker
        ports:
        - name: spring-boot-mongo-docker
          containerPort: 8080      
