--- 
apiVersion: v1
kind: Deployment
metadata: 
  labels: 
    name: spring-boot-mongo-docker
  name: spring-controller
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        name: spring-boot-mongo-docker
    spec: 
      containers: 
        - 
          image: raouagara/spring-boot-mongo
          imagePullPolicy: Never
          name: spring-boot-mongo-docker
          ports: 
            - 
              containerPort: 8080
              name: http-port
            - 
              containerPort: 50000
              name: jnlp-port

