apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: spring-boot-mongo-docker
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spring-boot-mongo-docker
    spec:
      containers:
      - image: raouagara/spring-boot-mongo
        name: spring-boot-mongo-docker
        ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
